/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_w_login (void);
GtkWidget* create_inscription (void);
GtkWidget* create_etud_niv (void);
GtkWidget* create_insc_succe (void);
GtkWidget* create_w_etud (void);
GtkWidget* create_w_tech (void);
GtkWidget* create_w_nutr (void);
GtkWidget* create_w_foyer (void);
GtkWidget* create_w_resto (void);
GtkWidget* create_gestion_user (void);
GtkWidget* create_modifier_user (void);
GtkWidget* create_niv_etud (void);
GtkWidget* create_not_found (void);
GtkWidget* create_confirm_supp (void);
GtkWidget* create_edit_niv_etud (void);
GtkWidget* create_copyright (void);
GtkWidget* create_gerer_le_stock (void);
GtkWidget* create_bhy_afficher (void);
GtkWidget* create_bhysucc (void);
GtkWidget* create_bhyerreur (void);
GtkWidget* create_bhy_modifier (void);
GtkWidget* create_ajouter_cap (void);
GtkWidget* create_afficher_cap (void);
GtkWidget* create_supprimer_cap (void);
GtkWidget* create_modifier_cap (void);
GtkWidget* create_tache2_cap (void);
GtkWidget* create_calcul_cap (void);
